---
- name: Install monitoring dependencies (Debian)
  ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Deploy monitoring scripts
  ansible.builtin.include_tasks: scripts.yml

- name: Configure systemd timer (Debian)
  ansible.builtin.include_tasks: systemd.yml
  when: ansible_os_family == "Debian"
