---
- name: Find all host rrd-init scripts
  ansible.builtin.find:
    paths: "{{ monitoring_base_path }}/host"
    patterns: "rrd-init*.sh"
  register: host_rrd_scripts

- name: Initialize host RRD databases
  ansible.builtin.command:
    cmd: "{{ item.path }}"
  loop: "{{ host_rrd_scripts.files }}"
  loop_control:
    label: "{{ item.path | basename }}"
  register: host_rrd_results
  changed_when: "'CREATED' in host_rrd_results.stdout"
