---
- name: Deploy services
  ansible.builtin.include_tasks: deploy.yml
  loop: "{{ enabled_services | intersect(deploy_services.split(',')) if deploy_services is defined else enabled_services }}"
  loop_control:
    loop_var: service_name
  tags:
    - services
