---
- name: Install nfs-kernel-server
  ansible.builtin.apt:
    name: nfs-kernel-server
    state: present
    update_cache: true

- name: Configure /etc/exports
  ansible.builtin.template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: "0644"
  notify: Re-export NFS shares

- name: Enable and start nfs-kernel-server
  ansible.builtin.systemd:
    name: nfs-kernel-server
    enabled: true
    state: started
