docker_data_root: "/mnt/raid/docker"

nfs_exports:
  - path: /mnt/raid
    clients:
      - network: 10.0.0.0/24
        options: rw,sync,no_subtree_check,no_root_squash
      - network: 10.0.1.0/24
        options: rw,sync,no_subtree_check,no_root_squash
  - path: /media/data
    clients:
      - network: 10.0.0.0/24
        options: rw,sync,no_subtree_check,no_root_squash,fsid=1
      - network: 10.0.1.0/24
        options: rw,sync,no_subtree_check,no_root_squash,fsid=1

enabled_services:
  # Networking
  - pihole
  - caddy-docker-proxy
  - cloudflare-ddns

  - tailscale
  # Media streaming
  - jellyfin
  - navidrome
  # Media management
  - radarr
  - sonarr
  - lidarr
  - bazarr
  - prowlarr
  - jellyseerr
  # Downloading
  - qbittorrent
  - slskd
  - unpackerr
  - flaresolverr

  # Photos
  - immich
  # Admin

  - scrutiny
  - jfa-go
  # Backup
  - borgmatic
  # Music Discovery
  - discoverylastfm
  # Notes
  - obsidian-livesync

  # Home Automation
  - homeassistant

  # Monitoring
  - monitoring

# GPU
render_group: "110"
gpu_device: "/dev/dri/renderD128"

# Scrutiny disk devices
scrutiny_devices:
  - /dev/sda
  - /dev/sdb
  - /dev/sdc
  - /dev/sdd
  - /dev/sde

# Monitoring
monitoring_host_custom_templates:
  - { src: smartctl-collect.sh.j2, dest: host/collect-smartctl.sh }

# Tailscale
tailscale_hostname: "media-pacheco"

