all:
  children:
    nixos:
      hosts:
        transcoder:
          ansible_host: 10.0.0.11
          ansible_user: skynet
          ansible_connection: ssh
    deb:
      hosts:
        nas:
          ansible_host: 10.0.0.2
          ansible_user: skynet
          ansible_connection: ssh
