background #000000
foreground #b9b9b9
cursor #bbbbbb
selection_background #b9b9b9
color0 #000000
color8 #000000
color1 #e8331c
color9 #df5a4f
color2 #68c156
color10 #76b768
color3 #f1d32b
color11 #eed64a
color4 #1c98e8
color12 #387bd2
color5 #8e69c8
color13 #957bbd
color6 #1c98e8
color14 #3d96e2
color7 #b9b9b9
color15 #b9b9b9
selection_foreground #212324

font_family FiraCode Nerd Font Mono
font_size 10.0
window_alert_on_bell yes
bell_border_color #ffc800
enable_audio_bell no
background_opacity 0.85
tab_bar_style powerline
tab_powerline_style round

allow_remote_control socket-only
listen_on unix:/tmp/kitty-{kitty_pid}

open_url_with xdg-open
clipboard_control write-clipboard write-primary read-clipboard read-primary

map ctrl+shift+t new_tab_with_cwd
